import { Kalam, Neucha } from "next/font/google";
import "./globals.css";
import FooterWeb from "./_components/footer";
import NewNavbar from "./_components/newnavbar";

const kalam = Kalam({ 
  subsets: ["latin"], 
  variable: '--font-sans', 
  weight: '300'
});
const neucha = Neucha({
  subsets: ['latin'],
  variable: '--font-neucha',
  weight: '400'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`${neucha.variable} font-neucha`}> 
        <NewNavbar/>
        {children}
        <FooterWeb />
        </body>
      </html>
      
  );
}
